# Generated by Django 2.1.3 on 2018-12-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181203_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_id',
            field=models.CharField(default=1010, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Seat'),
        ),
    ]
