# Generated by Django 2.1.3 on 2018-12-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181203_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_id',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='body',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='block',
            new_name='x',
        ),
        migrations.AddField(
            model_name='reservation',
            name='secret',
            field=models.CharField(default=1010, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='y',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.IntegerField(default='1'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
