# Generated by Django 2.1.3 on 2018-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181204_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='x',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='y',
            field=models.FloatField(default='0.0'),
        ),
    ]
