# Generated by Django 2.1.3 on 2018-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181204_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='x',
            field=models.FloatField(default='0.1'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='y',
            field=models.FloatField(default='0.1'),
        ),
    ]
