# Generated by Django 2.1.3 on 2018-12-12 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181204_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('res_id', models.IntegerField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seat', models.IntegerField(default='1')),
                ('secret', models.CharField(max_length=200)),
                ('x', models.FloatField(default='0.1')),
                ('y', models.FloatField(default='0.1')),
                ('note', models.TextField(blank=True)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
